import { StyleSheet } from 'react-native';
import { radius, spacing } from '../core/theme/theme';

export const styles = StyleSheet.create({
  card: { borderRadius: radius.lg, borderWidth: 1, padding: spacing.md, gap: 12 },
  cardLocked: { opacity: 0.62 },
  top: { flexDirection: 'row', gap: 13, alignItems: 'center' },
  icon: { width: 54, height: 54, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  iconLocked: { opacity: 0.5 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  name: { flex: 1, fontSize: 16.5, fontWeight: '800', letterSpacing: -0.2 },
  nameLocked: { opacity: 0.6 },
  chips: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  description: { fontSize: 13.5, lineHeight: 19 },
  descriptionLocked: { opacity: 0.55 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 9, borderTopWidth: 1, borderBottomWidth: 1 },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaText: { fontSize: 12, fontWeight: '600' },
  sep: { width: 1, height: 12 },
  lockBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
