import { StyleSheet } from 'react-native';
import { radius, spacing } from '../core/theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  topBar: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 10 },
  iconBtn: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
  topTitle: { color: '#fff', fontSize: 15, fontWeight: '800' },
  topSubtitle: { color: '#8E97C0', fontSize: 11.5, fontWeight: '600', marginTop: 1 },
  topProgressTrack: { height: 3, backgroundColor: 'rgba(255,255,255,0.09)' },
  topProgressFill: { height: 3 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10 },
  loadingText: { color: '#fff', fontSize: 14.5, fontWeight: '700' },
  loadingHint: { color: '#7C86B0', fontSize: 12 },
  bottomWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(12,15,30,0.94)' },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  toolBtn: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
  toolbarSep: { width: 1, height: 22, backgroundColor: 'rgba(255,255,255,0.14)', marginHorizontal: 6 },
  pageBadge: { paddingHorizontal: 14, height: 40, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center', minWidth: 78 },
  pageBadgeText: { color: '#fff', fontWeight: '800', fontSize: 13.5 },
  zoomBadge: { paddingHorizontal: 10, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', minWidth: 58, backgroundColor: 'rgba(255,255,255,0.06)' },
  zoomText: { color: '#C6CCEA', fontWeight: '800', fontSize: 12.5 },
  toast: {
    position: 'absolute',
    top: 96,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(18,22,44,0.96)',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: radius.pill,
    borderWidth: 1,
  },
  toastText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  exitFullscreen: {
    position: 'absolute',
    right: 16,
    bottom: 30,
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: 'rgba(20,24,48,0.86)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(4,6,16,0.6)' },
  sheet: {
    backgroundColor: '#141834',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: spacing.md,
    paddingTop: 10,
  },
  sheetHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.25)', alignSelf: 'center', marginBottom: 12 },
  sheetTitle: { color: '#fff', fontSize: 17, fontWeight: '800', marginBottom: 10 },
  outlineRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11 },
  outlineNum: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  outlineNumText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  outlineLabel: { flex: 1, color: '#D9DDF2', fontSize: 14, fontWeight: '600' },
});
